import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'
import openapiSidebar from './docs/api/generated/sidebar'

const sidebars: SidebarsConfig = {
  main: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'SDKs',
      link: { type: 'doc', id: 'sdks/index' },
      items: [{ type: 'autogenerated', dirName: 'sdks' }],
    },
    {
      type: 'category',
      label: 'Frameworks',
      items: [{ type: 'autogenerated', dirName: 'frameworks' }],
    },
  ],
  /** Generated by `docusaurus gen-api-docs locksmith` — do not hand-edit `docs/api/generated/sidebar.ts`. */
  api: openapiSidebar,
}

export default sidebars
